#include "pet_unlock_table.h"

static const pet_unlock_record_t k_pet_unlock_table[] = {
    {PET_SPECIES_QING_LONG, PET_UNLOCK_TYPE_PET_SPECIES, PET_RARITY_LEGENDARY,
     PET_SPECIES_QING_LONG, 0u, 11001u, PET_UNLOCK_FLAG_DEFAULT},
    {PET_SPECIES_ZHU_QUE, PET_UNLOCK_TYPE_PET_SPECIES, PET_RARITY_LEGENDARY,
     PET_SPECIES_ZHU_QUE, 0u, 11011u, PET_UNLOCK_FLAG_DEFAULT},
    {PET_SPECIES_XUAN_WU, PET_UNLOCK_TYPE_PET_SPECIES, PET_RARITY_LEGENDARY,
     PET_SPECIES_XUAN_WU, 0u, 11021u, PET_UNLOCK_FLAG_DEFAULT},
    {PET_SPECIES_FROST_WHITE_TIGER, PET_UNLOCK_TYPE_PET_SPECIES, PET_RARITY_LEGENDARY,
     PET_SPECIES_FROST_WHITE_TIGER, 0u, 11031u, PET_UNLOCK_FLAG_DEFAULT},
    {PET_SPECIES_QI_LIN, PET_UNLOCK_TYPE_PET_SPECIES, PET_RARITY_RARE, PET_SPECIES_QI_LIN,
     0u, 11041u, PET_UNLOCK_FLAG_DEFAULT},
    {PET_SPECIES_NINE_TAILED_FOX, PET_UNLOCK_TYPE_PET_SPECIES, PET_RARITY_RARE,
     PET_SPECIES_NINE_TAILED_FOX, 0u, 11051u, PET_UNLOCK_FLAG_DEFAULT},
    {PET_SPECIES_TAO_TIE, PET_UNLOCK_TYPE_PET_SPECIES, PET_RARITY_RARE, PET_SPECIES_TAO_TIE,
     0u, 11061u, PET_UNLOCK_FLAG_DEFAULT},
    {PET_SPECIES_QIONG_QI, PET_UNLOCK_TYPE_PET_SPECIES, PET_RARITY_RARE,
     PET_SPECIES_QIONG_QI, 0u, 11071u, PET_UNLOCK_FLAG_DEFAULT},
    {PET_SPECIES_TAO_WU, PET_UNLOCK_TYPE_PET_SPECIES, PET_RARITY_RARE, PET_SPECIES_TAO_WU,
     0u, 11081u, PET_UNLOCK_FLAG_DEFAULT},
    {PET_SPECIES_HUN_DUN, PET_UNLOCK_TYPE_PET_SPECIES, PET_RARITY_RARE,
     PET_SPECIES_HUN_DUN, 0u, 11091u, PET_UNLOCK_FLAG_DEFAULT},
    {PET_SPECIES_BAI_ZE, PET_UNLOCK_TYPE_PET_SPECIES, PET_RARITY_COMMON, PET_SPECIES_BAI_ZE,
     0u, 11101u, PET_UNLOCK_FLAG_DEFAULT},
    {PET_SPECIES_LU_SHU, PET_UNLOCK_TYPE_PET_SPECIES, PET_RARITY_COMMON, PET_SPECIES_LU_SHU,
     0u, 11111u, PET_UNLOCK_FLAG_DEFAULT},
    {PET_SPECIES_QING_NIAO, PET_UNLOCK_TYPE_PET_SPECIES, PET_RARITY_COMMON,
     PET_SPECIES_QING_NIAO, 0u, 11121u, PET_UNLOCK_FLAG_DEFAULT},
    {PET_SPECIES_DANG_KANG, PET_UNLOCK_TYPE_PET_SPECIES, PET_RARITY_COMMON,
     PET_SPECIES_DANG_KANG, 0u, 11131u, PET_UNLOCK_FLAG_DEFAULT},
    {PET_SPECIES_BI_FANG, PET_UNLOCK_TYPE_PET_SPECIES, PET_RARITY_COMMON,
     PET_SPECIES_BI_FANG, 0u, 11141u, PET_UNLOCK_FLAG_DEFAULT},
    {PET_SPECIES_JING_WEI, PET_UNLOCK_TYPE_PET_SPECIES, PET_RARITY_COMMON,
     PET_SPECIES_JING_WEI, 0u, 11151u, PET_UNLOCK_FLAG_DEFAULT},
    {PET_SPECIES_FU_ZHU, PET_UNLOCK_TYPE_PET_SPECIES, PET_RARITY_COMMON, PET_SPECIES_FU_ZHU,
     0u, 11161u, PET_UNLOCK_FLAG_DEFAULT},
    {PET_SPECIES_CHI_RU, PET_UNLOCK_TYPE_PET_SPECIES, PET_RARITY_COMMON, PET_SPECIES_CHI_RU,
     0u, 11171u, PET_UNLOCK_FLAG_DEFAULT},
    {2001u, PET_UNLOCK_TYPE_FOOD_CARD, PET_RARITY_COMMON, 2001u, 25u, 12001u,
     PET_UNLOCK_FLAG_DEFAULT},
    {3001u, PET_UNLOCK_TYPE_COMPANION_CARD, PET_RARITY_RARE, 3001u, 1u, 13001u,
     PET_UNLOCK_FLAG_DEFAULT},
    {4001u, PET_UNLOCK_TYPE_EQUIPMENT, PET_RARITY_RARE, 4001u, 75u, 14001u,
     PET_UNLOCK_FLAG_DEFAULT},
    {5001u, PET_UNLOCK_TYPE_HOME_ASSET, PET_RARITY_COMMON, 5001u, 50u, 15001u,
     PET_UNLOCK_FLAG_DEFAULT},
};

const pet_unlock_record_t* pet_unlock_find(uint16_t unlock_id) {
  uint16_t i;
  for (i = 0u; i < pet_unlock_count(); ++i) {
    if (k_pet_unlock_table[i].unlock_id == unlock_id) {
      return &k_pet_unlock_table[i];
    }
  }
  return 0;
}

const pet_unlock_record_t* pet_unlock_at(uint16_t index) {
  if (index >= pet_unlock_count()) {
    return 0;
  }
  return &k_pet_unlock_table[index];
}

uint16_t pet_unlock_count(void) {
  return (uint16_t)(sizeof(k_pet_unlock_table) / sizeof(k_pet_unlock_table[0]));
}

pet_result_t pet_unlock_validate_record(const pet_unlock_record_t* record) {
  if (record == 0 || record->unlock_id == 0u || record->target_id == 0u) {
    return PET_RESULT_INVALID_ARGUMENT;
  }
  switch (record->unlock_type) {
    case PET_UNLOCK_TYPE_PET_SPECIES:
      return pet_species_find(record->target_id) != 0 ? PET_RESULT_OK : PET_RESULT_INVALID_ARGUMENT;
    case PET_UNLOCK_TYPE_FOOD_CARD:
    case PET_UNLOCK_TYPE_COMPANION_CARD:
    case PET_UNLOCK_TYPE_EQUIPMENT:
    case PET_UNLOCK_TYPE_HOME_ASSET:
      return PET_RESULT_OK;
    default:
      return PET_RESULT_UNSUPPORTED;
  }
}
